// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';


console.log("Testing ! One Two... One Two !!!");

function verifyTree(tree) {
  if (typeof tree === "number") {
    if (tree !== 0) {
      return "It's a Maple";
    } else {
      return "It's a Pine!";
    }
  } else {
    var anyOtherTree = tree[0];
    if (anyOtherTree === "Black Lotus") {
      return "Holly SH***!";
    } else {
      return "Look, it's a " + (anyOtherTree + "!");
    }
  }
}

exports.verifyTree = verifyTree;
/*  Not a pure module */
